-- | Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with $1$ and $2$, the first  terms will be:
--
-- [ 1,2,3,5,8,13,21,34,55,89,...]
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

module Problems.Problem2 (
    solution
  , fibs
) where

-- | Stream of Fibonacci numbers,
--  i.e. infinite list of Fibonacci numbers.
-- starting with 1, 2, ...
fibs :: [Integer]
fibs = 1 : 2 : zipWith (+) fibs (tail fibs)

-- >>> take 10 fibs
-- [1,2,3,5,8,13,21,34,55,89]

-- | Sum of even-valued terms in the Fibonacci sequence
-- whose values do not exceed four million.
solution :: Integer
solution = sum $ filter even $ takeWhile (< 4000000) fibs

-- >>> solution
-- 4613732
